from iter import *

if __name__ == "__main__":
  fiter = UpDownFile('wikipedia-excerpt.txt')
  iter(fiter)
  print('### Let\'s go up and down for a while') 
  print(next(fiter))
  print(next(fiter))
  print(next(fiter))
  print(next(fiter))
  print(next(fiter))
  print(next(fiter))
  fiter.ungetw()
  fiter.ungetw()
  fiter.ungetw()
  print(next(fiter))
  print(next(fiter))
  fiter.ungetw()
  fiter.ungetw()
  print(next(fiter))
  fiter.ungetw()
  fiter.ungetw()
  fiter.ungetw()
  print(next(fiter))
  print(next(fiter))
  print(next(fiter))
  fiter.ungetw()
  print('### Let\'s finish the iteration') 
  try:
    while True:
      print(next(fiter))
  except StopIteration: pass
  print('### Let\'s restart the iteration') 
  iter(fiter)
  print(next(fiter))
  print(next(fiter))
  print(next(fiter))
  fiter.ungetw()
  print(next(fiter))
